export const RECEIPT_LIST = [
    {
        order_number: 1102124513521,
        state: "배송중",
        date: new Date("2025-12-02 18:06:20"),
        address: "봉수대로 1440번길 10",
        payment: "무통장입금",
        products: [
            {
                name: "아이소핑크",
                sub: "10t",
                option: ["60*45"],
                price: 2000,
                sale: 0,
                amount: 1,
            },
            {
                name: "아이소핑크",
                sub: "20t",
                option: ["60*45"],
                price: 3000,
                sale: 0,
                amount: 1,
            },
            {
                name: "아이소핑크",
                sub: "30t",
                option: ["60*45"],
                price: 4000,
                sale: 0,
                amount: 1,
            },
            {
                name: "아이소핑크",
                sub: "40t",
                option: ["60*45"],
                price: 5000,
                sale: 0,
                amount: 1,
            },
            {
                name: "아이소핑크",
                sub: "50t",
                option: ["60*45"],
                price: 6000,
                sale: 0,
                amount: 1,
            },
            {
                name: "아이소핑크",
                sub: "60t",
                option: ["60*45"],
                price: 7000,
                sale: 0,
                amount: 1,
            },
            {
                name: "아이소핑크",
                sub: "70t",
                option: ["60*45"],
                price: 8000,
                sale: 0,
                amount: 1,
            },
            {
                name: "아이소핑크",
                sub: "80t",
                option: ["60*45"],
                price: 9000,
                sale: 0,
                amount: 1,
            },
            {
                name: "아이소핑크",
                sub: "90t",
                option: ["60*45"],
                price: 10000,
                sale: 0,
                amount: 1,
            },
            {
                name: "아이소핑크",
                sub: "100t",
                option: ["60*45"],
                price: 11000,
                sale: 0,
                amount: 1,
            },
        ],
        delivery_fee: 60000,
        coupon: 0,
        discount: 10,
        total: {
            price: 125000,
            sale: 112500,
        },
        memo: "앞에 놔주세요",
    },
    {
        order_number: 1102124512214,
        state: "픽업완료",
        date: new Date("2025-11-18 10:30:20"),
        address: "봉수대로 1440번길 10",
        payment: "무통장입금",
        products: [
            {
                name: "파이프 원형 롱소켓",
                sub: "25mm",
                option: [],
                price: 2200,
                sale: 10,
                amount: 100,
            },
            {
                name: "파이프 원형 롱소켓",
                sub: "20mm",
                option: [],
                price: 2000,
                sale: 10,
                amount: 100,
            },
        ],
        delivery_fee: 60000,
        coupon: 1000,
        discount: 10,
        total: {
            price: 480000,
            sale: 402300,
        },
        memo: "앞에 놔주세요",
    },
    {
        order_number: 1102124512213,
        state: "주문취소",
        date: new Date("2025-11-18 10:00:10"),
        address: "봉수대로 1440번길 10",
        payment: "무통장입금",
        products: [
            {
                name: "파이프 원형 롱소켓",
                sub: "25mm",
                option: [],
                price: 2200,
                sale: 10,
                amount: 100,
            },
            {
                name: "파이프 원형 롱소켓",
                sub: "20mm",
                option: [],
                price: 2000,
                sale: 10,
                amount: 100,
            },
        ],
        delivery_fee: 60000,
        coupon: 1000,
        discount: 10,
        total: {
            price: 480000,
            sale: 402300,
        },
        memo: "앞에 놔주세요",
    },
];
